config/routes.rb
Rails.application.routes.draw do
  constraints(subdomain: /siteadmin/) do
    ActiveAdmin.routes(self)

    namespace :admin do
      resource :session, only: %w(new create destroy)
      resources :dashboard, only: :index
      resources :campaign_admins
      resources :tenants
      resources :campaigns do
        resources :campaign_influencers
        resource :influencer_searches, only: %w(new create)
        resources :tasks
      end
      resources :influencers
      resources :influencers_imports, only: %i(index create)

      scope '/:type/:parent_id', constraints: { type: /(campaign|tenant)/ } do
        resources :contacts
      end

      resources :tickets, only: %w(index update) do
        resources :replies, only: %w(new create)
      end

      resources :export_tenants, only: %w(index create)
      resources :import_tenants, only: %w(index create)
    end

    root to: 'admin/dashboard#index'
  end

  constraints(subdomain: /^(?!siteadmin)(\w+)/) do
    resources :tenants
    resource :sessions, only: %w(new create destroy)

    root to: 'tenants#index'

    resources :campaigns do
      resource :forum, only: :show
      resources :tasks, path: 'tasks/:type', constraints: { type: /(uncompleted|completed)/ }, defaults: { type: 'uncompleted' } do
        resource :survey, only: :show
        resource :task_users, only: :create
      end
    end

    resources :forum, only: [] do
      resources :products
    end

    resources :products, only: [] do
      resources :categories
    end

    resources :categories, only: [] do
      resources :topics
    end

    resources :topics, only: [] do
      resources :posts
    end

    resources :campaign_influencers, only: %w(edit update)
  end

  resource :locales, only: :update
  resource :password_changes, only: %w(new edit update create)
  resources :password_resets, except: %w(index destroy)
  resources :tickets, only: %w(new create)
  resources :avatars, only: %w(new update)
end

app/views/shared/_avatar_modal.html.slim
#changeAvatar.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5.modal-title= I18n.t('.avatars.change_avatar')
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
      .modal-body
        = simple_form_for 'user', url: avatar_path(subdomain == 'siteadmin' ? current_user : current_tenant_user), method: :patch do |f|
          = f.input :avatar, as: :file, label: false
          br
          = f.submit I18n.t('.avatars.upload')
      .modal-footer
        button.btn.btn-secondary data-dismiss="modal" type="button"= I18n.t('.close')

app/views/shared/_campaign_navigation.html.slim
.row.campaign-logos
  = render partial: 'campaigns/logo', collection: campaign.logos, as: :logo

- if (current_tenant_user&.influencer? && campaign_influencer&.approved?) || !current_tenant_user.influencer?
  .btn-group.navigation
    - if current_tenant_user.influencer? || current_tenant_user.campaign_contact? || current_tenant_user.tenant_contact?
      => link_to I18n.t('.tasks.tasks'), campaign_tasks_path(campaign, :uncompleted), class: "btn btn-secondary #{ 'active btn-primary' if current_page?(campaign_tasks_path(campaign, :uncompleted))}"
    - if current_tenant_user.influencer?
      => link_to I18n.t('.tasks.completed_tasks'), campaign_tasks_path(campaign, :completed), class: "btn btn-secondary #{ 'active btn-primary' if current_page?(campaign_tasks_path(campaign, :completed))}"
    - if campaign.use_forum
      = link_to t('.campaigns.forum'), campaign_forum_path(campaign), class: "btn btn-secondary #{ 'active btn-primary' if current_page?(campaign_forum_path(campaign))}"
    = link_to I18n.t('.tickets.help'), new_ticket_path(campaign_id: campaign.id), class: "btn btn-secondary #{ 'active btn-primary' if current_page?(new_ticket_path)}"

  br
  .row
    .col-sm-12.col-md-12.col-lg-12
      .float-left
        h3 #{I18n.t('.campaigns.campaign')}: #{campaign&.project_name}
  hr

  - if product
    br
    .row
      .col-sm-6
        .float-left
          h4 #{I18n.t('.products.product')}: #{product.title}
      - if category
        .col-sm-6
          .float-left
            h4 #{I18n.t('.categories.category')}: #{category.title}
    hr

  - if topic
    br
    .row
      .col-sm-6
        .float-left
          h4 #{I18n.t('.topics.topic')}: #{topic.subject} #{"(#{I18n.t('.topics.closed')})" if topic.closed}
          - if topic.referred
            p
              | #{I18n.t('.topics.duplicate')}:
              =< link_to topic.referred.subject, category_topic_path(topic.referred.category,
                                                                    topic.referred)
      - if current_tenant_user.campaign_admin?
        = render 'topics/admin_panel'
    hr
- else
  - if campaign_influencer&.contract&.url
    = render 'campaign_influencers/contract_uploaded'
  - else
    .contract-navigation
      = link_to I18n.t('.download_contract'), campaign.contract.url, class: 'btn btn-primary', target: '_blank' if campaign.contract.url
      = link_to I18n.t('.upload_contract'), edit_campaign_influencer_path(campaign_influencer),
                                   class: 'btn btn-primary', remote: true
      .row
        .col-sm-6.campaign-influencer-contract

app/views/shared/_language_modal.html.slim
#changeLanguage.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5.modal-title= I18n.t('.change_language')
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
      .modal-body
        => link_to 'English', locales_path(language: :English), method: :patch, class: 'btn btn-primary'
        => link_to 'Spanish', locales_path(language: :Spanish), method: :patch, class: 'btn btn-primary'
        = link_to 'Portuguese', locales_path(language: :Portuguese), method: :patch, class: 'btn btn-primary'
      .modal-footer
        button.btn.btn-secondary data-dismiss="modal" type="button"= I18n.t('.close')

app/views/shared/_modal.html.slim
.modal.fade[role='dialog' id="#{id}"]
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title
          .float-left= title
        button.close#close_modal[type='button' data-dismiss='modal']
          | ×
      .modal-body= render form, parent_id: local_assigns[:parent_id]

app/views/shared/_password_reset_modal.html.slim
#password-reset-modal.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-body
        - if user
          = I18n.t('.modal.password_reset_sent')
        - else
          = I18n.t('.modal.password_reset_not_found')
      .modal-footer
        button.btn.btn-secondary data-dismiss="modal" type="button"= I18n.t('.close')