config/routes.rb
Rails.application.routes.draw do
  constraints(subdomain: /siteadmin/) do
    ActiveAdmin.routes(self)

    namespace :admin do
      resource :session, only: %w(new create destroy)
      resources :dashboard, only: :index
      resources :campaign_admins
      resources :tenants
      resources :campaigns do
        resources :campaign_influencers
        resource :influencer_searches, only: %w(new create)
        resources :tasks
      end
      resources :influencers
      resources :influencers_imports, only: %i(index create)

      scope '/:type/:parent_id', constraints: { type: /(campaign|tenant)/ } do
        resources :contacts
      end

      resources :tickets, only: %w(index update) do
        resources :replies, only: %w(new create)
      end

      resources :export_tenants, only: %w(index create)
      resources :import_tenants, only: %w(index create)
    end

    root to: 'admin/dashboard#index'
  end

  constraints(subdomain: /^(?!siteadmin)(\w+)/) do
    resources :tenants
    resource :sessions, only: %w(new create destroy)

    root to: 'tenants#index'

    resources :campaigns do
      resource :forum, only: :show
      resources :tasks, path: 'tasks/:type', constraints: { type: /(uncompleted|completed)/ }, defaults: { type: 'uncompleted' } do
        resource :survey, only: :show
        resource :task_users, only: :create
      end
    end

    resources :forum, only: [] do
      resources :products
    end

    resources :products, only: [] do
      resources :categories
    end

    resources :categories, only: [] do
      resources :topics
    end

    resources :topics, only: [] do
      resources :posts
    end

    resources :campaign_influencers, only: %w(edit update)
  end

  resource :locales, only: :update
  resource :password_changes, only: %w(new edit update create)
  resources :password_resets, except: %w(index destroy)
  resources :tickets, only: %w(new create)
  resources :avatars, only: %w(new update)
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :tenant
  belongs_to :campaign_influencer
  has_many :replies

  after_create :notify_tenant_owner

  private

  def notify_tenant_owner
    campaign_influencer ? UserMailer.admin_ticket_notification(campaign_influencer.campaign.owner, self).deliver! : notify_admins
  end

  def notify_admins
    User::CampaignAdmin.find_each do |admin|
      UserMailer.admin_ticket_notification(admin, self).deliver!
    end
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < AdminsController
  before_action :close_ticket, if: proc { params[:closed] }, only: :update

  expose(:tickets) { Ticket.all.order(id: :desc) }
  expose(:ticket)

  def update
    redirect_to admin_tickets_path
  end

  private

  def close_ticket
    ticket.update(closed: params[:closed])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  expose(:campaign) { Campaign.find_by(id: params[:campaign_id]) }
  expose(:ticket)

  layout :help_layout

  def create
    ticket.update(ticket_params)
    flash[:notice] = I18n.t('.tickets.sent')
    redirect_to root_path
  end

  private

  def ticket_params
    params.require(:ticket).permit(:email, :text).merge(tenant: tenant)
  end

  def tenant
    @tenant ||= Tenant.where('lower(name) = lower(?)', request.subdomains[0]).first
  end

  def help_layout
    subdomain == 'siteadmin' || campaign.nil? ? 'application' : 'tenant'
  end
end

app/views/admin/tickets/_row.html.slim
.ticket data-ticket-id=ticket.id
  .row
    .col-sm-12.col-md-1.col-lg-1
      = ticket.id
    .col-sm-12.col-md-4.col-lg-4
      = ticket.email
    .col-sm-12.col-md-4.col-lg-4
      = ticket.text
      - if ticket.campaign_influencer
        span.only-mobile= link_to inline_svg('svg/file.svg'), ticket.campaign_influencer.contract.url , target: '_blank'
        span.only-desktop= link_to I18n.t('.download_contract'), ticket.campaign_influencer.contract.url, class: 'btn btn-primary', target: '_blank'
    .col-sm-12.col-md-5.col-lg-3
      - if ticket.closed
        .float-right
          span.only-mobile= link_to inline_svg('svg/reopen.svg', width: 32, height: 32), admin_ticket_path(ticket, closed: false), method: :put
          span.only-desktop= link_to I18n.t('.tickets.open'), admin_ticket_path(ticket, closed: false), method: :put, class: 'btn btn-primary'
      - else
        .float-left
          span.only-mobile= link_to inline_svg('svg/reply.svg'), new_admin_ticket_reply_path(ticket), remote: true
          span.only-desktop=> link_to I18n.t('.tickets.reply'),  new_admin_ticket_reply_path(ticket), remote: true, class: 'btn btn-primary'
        .float-right
          span.only-mobile=> link_to inline_svg('svg/cancel-circle.svg'), admin_ticket_path(ticket, closed: true), method: :put
          span.only-desktop=> link_to I18n.t('.tickets.close'), admin_ticket_path(ticket, closed: true), method: :put, class: 'btn btn-primary'
    .col-sm-12
      = ticket.created_at
hr

app/views/admin/tickets/index.html.slim
br
.row
  .col-sm-12.col-md-12.col-lg-12
    .float-left
      h4= t('.tickets.help_desk')
br
.row
  .col-sm-12
    .tickets= render partial: 'row', collection: tickets, as: :ticket