config/routes.rb
Rails.application.routes.draw do
  constraints(subdomain: /siteadmin/) do
    ActiveAdmin.routes(self)

    namespace :admin do
      resource :session, only: %w(new create destroy)
      resources :dashboard, only: :index
      resources :campaign_admins
      resources :tenants
      resources :campaigns do
        resources :campaign_influencers
        resource :influencer_searches, only: %w(new create)
        resources :tasks
      end
      resources :influencers
      resources :influencers_imports, only: %i(index create)

      scope '/:type/:parent_id', constraints: { type: /(campaign|tenant)/ } do
        resources :contacts
      end

      resources :tickets, only: %w(index update) do
        resources :replies, only: %w(new create)
      end

      resources :export_tenants, only: %w(index create)
      resources :import_tenants, only: %w(index create)
    end

    root to: 'admin/dashboard#index'
  end

  constraints(subdomain: /^(?!siteadmin)(\w+)/) do
    resources :tenants
    resource :sessions, only: %w(new create destroy)

    root to: 'tenants#index'

    resources :campaigns do
      resource :forum, only: :show
      resources :tasks, path: 'tasks/:type', constraints: { type: /(uncompleted|completed)/ }, defaults: { type: 'uncompleted' } do
        resource :survey, only: :show
        resource :task_users, only: :create
      end
    end

    resources :forum, only: [] do
      resources :products
    end

    resources :products, only: [] do
      resources :categories
    end

    resources :categories, only: [] do
      resources :topics
    end

    resources :topics, only: [] do
      resources :posts
    end

    resources :campaign_influencers, only: %w(edit update)
  end

  resource :locales, only: :update
  resource :password_changes, only: %w(new edit update create)
  resources :password_resets, except: %w(index destroy)
  resources :tickets, only: %w(new create)
  resources :avatars, only: %w(new update)
end

app/models/user/campaign_admin.rb
class User::CampaignAdmin < User
  def campaign_admin?
    true
  end

  def influencer?
    false
  end
end

app/controllers/admin/campaign_admins_controller.rb
class Admin::CampaignAdminsController < AdminsController
  expose(:campaign_admin, model: User::CampaignAdmin)
  expose(:campaign_admins) { User::CampaignAdmin.all }

  def update
    create
  end

  def create
    if campaign_admin.update(admin_params)
      redirect_to admin_campaign_admins_path
    else
      flash[:error] = campaign_admin.errors.messages
      redirect_to :back
    end
  end

  def destroy
    campaign_admin.destroy
    redirect_to admin_campaign_admins_path
  end

  private

  def admin_params
    params.require(:user_campaign_admin).permit! if params[:user_campaign_admin]
  end
end

app/views/admin/campaign_admins/_form.html.slim
= simple_form_for campaign_admin, url: { controller: :campaign_admins, action: campaign_admin.new_record? ? :create : :update} do |f|
  .form-group= f.input :username, input_html: { class: 'form-control' }, required: true, label: I18n.t('.username')
  .form-group= f.input :first_name, input_html: { class: 'form-control' }, required: true, label: I18n.t('.first_name')
  .form-group= f.input :surname, input_html: { class: 'form-control' }, label: I18n.t('.patrimonial'), required: true
  .form-group= f.input :matrimonial_surname, input_html: { class: 'form-control' }, label: I18n.t('.matrimonial')
  .form-group= f.input :primary_language, input_html: { class: 'form-control' }, collection: User.primary_languages.keys, required: true, label: I18n.t('.influencers.primary_language')
  .form-group= f.input :email, input_html: { class: 'form-control' }, label: I18n.t('.email_address'), type: :email, required: true

  .form-group
    .float-left= f.submit I18n.t('.save'), class: 'btn btn-primary'
    .float-right= link_to I18n.t('.cancel'), admin_campaign_admins_path, class: 'btn btn-primary'

app/views/admin/campaign_admins/_new.html.slim
br
.row
  .float-left
    = I18n.t('.campaign_administrators')

.row
  .col-md-3.col-lg-4
  .col-sm-12.col-md-6.col-lg-4
    = render 'form'
  .col-md-3.col-lg-4

app/views/admin/campaign_admins/_row.html.slim
tr
  th= link_to admin.username, edit_admin_campaign_admin_path(admin)
  th= link_to admin.first_name, edit_admin_campaign_admin_path(admin)
  th= link_to admin.full_surname, edit_admin_campaign_admin_path(admin)
  th= link_to admin.email, edit_admin_campaign_admin_path(admin)
  th
    = link_to admin_campaign_admin_path(admin), method: :delete, data: { confirm: "Delete Campaign Admin: #{admin.username}?" } do
      | &#x2718

app/views/admin/campaign_admins/edit.html.slim
= render 'new'

app/views/admin/campaign_admins/index.html.slim
br
.row
  .col-sm-12.col-md-12.col-lg-12
    .float-left
      = I18n.t('.campaign_administrators')
    .float-right
      => link_to I18n.t('.new_campaign_administrator'), new_admin_campaign_admin_path, class: 'btn btn-primary'
br
.row
  .col-sm-12.col-md-12.col-lg-12
    table.table.table-striped
      tr
        th= I18n.t('.username')
        th= I18n.t('.first_name')
        th= I18n.t('.surname')
        th= I18n.t('.email')
        th= I18n.t('.delete')
      = render partial: 'row', collection: campaign_admins, as: :admin

app/views/admin/campaign_admins/new.html.slim
= render 'new'