config/routes.rb
Rails.application.routes.draw do
  constraints(subdomain: /siteadmin/) do
    ActiveAdmin.routes(self)

    namespace :admin do
      resource :session, only: %w(new create destroy)
      resources :dashboard, only: :index
      resources :campaign_admins
      resources :tenants
      resources :campaigns do
        resources :campaign_influencers
        resource :influencer_searches, only: %w(new create)
        resources :tasks
      end
      resources :influencers
      resources :influencers_imports, only: %i(index create)

      scope '/:type/:parent_id', constraints: { type: /(campaign|tenant)/ } do
        resources :contacts
      end

      resources :tickets, only: %w(index update) do
        resources :replies, only: %w(new create)
      end

      resources :export_tenants, only: %w(index create)
      resources :import_tenants, only: %w(index create)
    end

    root to: 'admin/dashboard#index'
  end

  constraints(subdomain: /^(?!siteadmin)(\w+)/) do
    resources :tenants
    resource :sessions, only: %w(new create destroy)

    root to: 'tenants#index'

    resources :campaigns do
      resource :forum, only: :show
      resources :tasks, path: 'tasks/:type', constraints: { type: /(uncompleted|completed)/ }, defaults: { type: 'uncompleted' } do
        resource :survey, only: :show
        resource :task_users, only: :create
      end
    end

    resources :forum, only: [] do
      resources :products
    end

    resources :products, only: [] do
      resources :categories
    end

    resources :categories, only: [] do
      resources :topics
    end

    resources :topics, only: [] do
      resources :posts
    end

    resources :campaign_influencers, only: %w(edit update)
  end

  resource :locales, only: :update
  resource :password_changes, only: %w(new edit update create)
  resources :password_resets, except: %w(index destroy)
  resources :tickets, only: %w(new create)
  resources :avatars, only: %w(new update)
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :topics, dependent: :destroy

  mount_base64_uploader :logo, LogoUploader
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_tenant_login

  expose(:category)
  expose(:product)
  expose(:forum) { product.forum }
  expose(:campaign) { forum.campaign }
  expose(:all_topics) { category.topics }

  layout 'tenant'

  def create
    head :no_content unless category.update(category_params)
  end

  def destroy
    category.destroy
  end

  private

  def category_params
    params.require(:category).permit(:title, :description, :user_id, :logo)
                             .merge(product_id: params[:product_id])
  end
end

app/views/categories/_form.html.slim
= simple_form_for :category, url: product_categories_path(product), remote: true do |f|
  = f.hidden_field :user_id, value: current_tenant_user.id
  .form-group= f.input :title, required: true, input_html: { class: 'form-control' }
  .form-group= f.input :description, as: :text, input_html: { class: 'form-control' }
  .form-group= f.input :logo, as: :file,
                       input_html: { class: 'form-control form-control-file',
                       accept: 'image/*' }, required: true
  .form-group
    .float-left= f.submit I18n.t('.save'), class: 'btn btn-primary'
    .float-right= link_to I18n.t('.cancel'), forum_product_path(product),
                                             class: 'btn btn-primary'

app/views/categories/_row.html.slim
tr data-category-id=category.id
  th= image_tag category.logo.url, width: 50, height: 50
  th= link_to category.title, product_category_path(category.product_id, category)
  th= category.description
  th= category.user.username
  th= category.created_at.strftime('%d %b %Y')
  - if current_tenant_user.campaign_admin?
    th
      = link_to product_category_path(category.product_id, category), remote: true, method: :delete,
        data: { confirm: "Delete #{I18n.t('.categories.category')}: #{category.title}?" } do
        | &#x2718

app/views/categories/show.html.slim
.row
  .col-sm-12
    .float-right
      button.btn.btn-primary[type='button' data-toggle='modal' data-target='#topic_modal']=I18n.t('.topics.new_topic')
      = render 'shared/modal', id: 'topic_modal',
                               parent_id: category.id,
                               title: I18n.t('.topics.new_topic'),
                               form: 'topics/form'

br
.row
  .col-sm-12
    .topics= render partial: 'topics/row', collection: all_topics, as: :topic